version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          # Group minor and patch dependencies which should be able to be applied blindly
          # This creates individual PRs for major updates
          dev-dependencies:
              update-types:
                  - 'minor'
                  - 'patch'

    - package-ecosystem: 'github-actions'
      # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
      directory: '/'
      schedule:
          interval: 'weekly'
